# Common responses about the company
phone_number = 'O telefone de contato é (41) 3014-9646 e WhatsApp é (41) 9 9264-1020'
email = 'O e-mail de contato é contato@m1motorscwb.com.br'
privacy_policy = 'Acesse através deste link: https://m1motors.com.br/politica-de-privacidade'
company_address = 'O endereço de todas as lojas está disponível neste link: https://m1motors.com.br/localizacao'
who_is = 'Fundada em 2020 por um visionário com ampla experiência no mercado automotivo, a M1 Motors é uma empresa do ramo automotivo que se destaca pela inovação. Sua localização estratégica em Shopping Centers proporciona aos clientes maior conforto e segurança durante todo o processo de compra e venda de veículos.'
company_website = 'Nosso site é: https://m1motors.com.br/'
more_information = 'Para mais informações entre em contato através do e-mail: contato@m1motorscwb.com.br ou WhatsApp (41) 9 9264-1020. Também estamos nas redes sociais como @m1motorsoficial'
help_how = 'Como posso te ajudar? Digite 0 para listar as opções ou sair para encerrar o chat'
unknown_option = 'Opção não reconhecida, favor tente novamente'

# Trained responses in PT-BR
training_data1 = [
    'Qual o telefone de contato?',
    phone_number,
    'Qual o e-mail de contato?',
    email,
    'Como eu acesso a politica de privacidade da empresa?',
    privacy_policy,
    'Qual o endereço?',
    company_address,
    'qual o endereço da loja',
    company_address,
    'loja',
    company_address,
    'Quem é a M1 Motors?',
    who_is,
    'Qual o site da empresa?',
    company_website,
    'Preciso de mais informações',
    more_information,
    'oi',
    help_how,
    'ola',
    help_how,
    'olá',
    help_how,
    'tudo bem?',
    help_how,
    'qual a forma de pagamento',
    more_information,
    'pagamento',
    more_information,
    'ajuda',
    more_information,
    'modelo de carro',
    more_information,
    'Quais marcas de veículos a M1 Motors oferece?',
    'A M1 Motors atualmente conta com 32 marcas diferentes em seu estoque, incluindo Volkswagen, Chevrolet, Renault, Fiat, Ford, Hyundai, Jeep, Honda, Toyota, Peugeot, Nissan e BMW',
    'Como posso entrar em contato com a M1 Motors?',
    'Você pode entrar em contato via WhatsApp (41) 9 9264-1020 ou pelo telefone (41) 3014-9646. Além disso, também estamos presentes no Instagram, Facebook e TikTok como @m1motorsoficial',
    'Qual é a especialidade da M1 Motors?',
    'A M1 Motors é conhecida por oferecer carros seminovos, usados e zero em Curitiba. Temos uma variedade de modelos de multimídias automotivas',
    'Qual é o horário de funcionamento da M1 Motors?',
    'A M1 Motors está aberta de segunda a sexta-feira, das 8h às 18h, e aos sábados, das 9h às 13h.',
    'Quais são os documentos necessários para comprar um veículo na M1 Motors?',
    'Para a compra de um veículo, você precisará apresentar RG, CPF, comprovante de residência e comprovante de renda.',
    'A M1 Motors oferece serviços de consórcio?',
    'Sim, temos opções de consórcio para quem deseja adquirir um veículo de forma parcelada.',
    'Quais são as opções de pagamento aceitas pela M1 Motors?',
    'Aceitamos pagamento à vista, financiamento bancário e cartões de crédito para aquisição de veículos.',
    'Quais são os benefícios de comprar um veículo seminovo na M1 Motors?',
    'Os veículos seminovos geralmente têm preços mais acessíveis e ainda contam com garantia e revisão prévia.',
    'quem é você?',
    who_is,
    'quem são vocês?',
    who_is,
    'endereço',
    company_address,
    'telefone',
    phone_number,
    'preciso de ajuda',
    more_information,
    'carro',
    more_information,
    'quero comprar um carro',
    more_information,
    'comprar',
    more_information,
    'compra de um veiculo',
    more_information,
    'vender',
    more_information,
    'quero vender um carro',
    more_information,
    'vender carro',
    more_information,
    'Vocês têm carros elétricos ou híbridos?',
    more_information,
    'Como posso entrar em contato com um vendedor?',
    more_information,
    'Vocês têm promoções especiais ou descontos atualmente?',
    more_information,
    'Vocês aceitam troca de veículos?',
    more_information,
    'Como posso agendar um test drive?',
    more_information,
    'preciso de ajuda pra comprar um carro',
    more_information
]

# Alternative questions based on the menu list
training_data2 = [
    '1',
    phone_number,
    '2',
    email,
    '3',
    privacy_policy,
    '4',
    company_address,
    '5',
    who_is,
    '6',
    company_website,
    '7',
    unknown_option,
    '8',
    unknown_option,
    '9',
    unknown_option,
    '10',
    unknown_option
]
